### ISSUE TITLE
Add option to allow interval refill to happen on interval boundary

### ISSUE THREAD

**Issue by siwhiting** [vladimir-bukhtoyarov/bucket4j#100]
We're keen to use the interval buckets (instead of greedy buckets), but would like the refill to happen on an interval boundary (i.e. start of second, minute, hour, day) rather than when the bucket is created.

The main reason for this, is to provide transparency to the end customer on when buckets are refilled.

For example:

- If we setup a bucket with 100 tokens that has a interval refill of 100 tokens every hour.
- Currently, if bucket is created 20 minutes past the hour, then it will get refilled 20 minutes past the next hour.
- If we were to create another bucket with same values but X minutes past the hour, then this would be refilled X minutes past the hour.

This is very confusing to customers, especially when they are testing the bucket4j behaviour.

A useful feature would be that when a bucket is created, there is an option that specifies that it should be refilled on the next interval boundary.

The intervals could be applied to second(?), minute, hour or day, and would need to accurate to at least 10ms.

This feature could also take into account the initial tokens for the bucket (though it won't be too difficult to do this ourselves).

For example:

- If we setup a bucket with 100 tokens that has a interval refill of 100 tokens every hour, specifying that the refill happens at start of an hour.
- bucket is created 20 minutes past the hour
- bucket gets initially created with 66 tokens (pro-rate of number of tokens for bucket with the time left to interval boundary) and refilled in 40 minutes (to align it to the hour boundary)
- after this first refill, it should there after be refilled with 100 tokens every 60 minutes.

I did notice that in original discussion of fixed interval buckets (https://github.com/vladimir-bukhtoyarov/bucket4j/issues/39), there was mention of "Instant timeOfFirstRefill" parameter that could have met this feature, but this wasn't implemented.

**Comment by vladimir-bukhtoyarov** [comment]
Looks like promising feature which moves library significantly forward from client experience point-of-view. I will provide mockup for the API today.

**Comment by vladimir-bukhtoyarov** [comment]
The mockup of API:
```java
/**
     * Creates the {@link Refill} that does refill of tokens in intervally manner.
     * "Intervally" in opposite to "greedy"  will wait until whole {@code period} will be elapsed before regenerate {@code tokens}.
     * In additional to {@link #intervally(long, Duration)}</p> this method makes the refill to happen on an interval boundary (i.e. start of second, minute, hour, day) 
     * rather than when the bucket is created. The stickiness boundary provided via parameter {@code sticknessPoint}.
     * 
     *
     * <p>
     * If {code useAdaptiveInitialTokens == true}, then the refill created by this method will also take into account the initial tokens for the bandwidth in following manner:
     * <ul>
     * <li>
     *    If we setup a bandwidth with 100 tokens that has a interval refill of 100 tokens every hour, specifying that the refill happens at start of an hour.
     * </li>
     * <li>
 *        Bucket is created 20 minutes past the hour.
     * </li>
     * <li>
     *    Bucket gets initially created with 66 tokens (pro-rate of number of tokens for bucket with the time left to interval boundary)
     *    and refilled in 40 minutes (to align it to the hour boundary).
     * </li>
     * <li>
     *    After this first refill, it should there after be refilled with 100 tokens every 60 minutes.
     * </li>
     * </ul>
     *
     * @param tokens amount of tokens
     * @param period the period within {@code tokens} will be fully regenerated
     * @param sticknessPoint the date which will be used as boundary for first refill, must be an date in the past.
     *
     * @return the {@link Refill} that does refill of tokens in intervally manner
     */
    public static Refill withStickyIntervall(long tokens, Duration period, Instant sticknessPoint, boolean useAdaptiveInitialTokens) {
        // ...
    }
```

Bellow the examples of usage.  @siwhiting keep in mind that if bandwidth capacity differs with refill tokens(4-th example), then rules for initial tokens calculation will be more difficult then you imagine
```java
// bind the refill to boundary of hour
        Instant sticknessPoint = ZonedDateTime.now().truncatedTo(ChronoUnit.HOURS).toInstant();

        // initial tokens 100
        Bandwidth.classic(100, Refill.withStickyIntervall(100, Duration.ofHours(1), sticknessPoint, false));

        // initial tokens 66
        Bandwidth.classic(100, Refill.withStickyIntervall(100, Duration.ofHours(1), sticknessPoint, true));

        // initial tokens 400
        Bandwidth.classic(400, Refill.withStickyIntervall(100, Duration.ofHours(1), sticknessPoint, false));

        // initial tokens 366
        Bandwidth.classic(400, Refill.withStickyIntervall(100, Duration.ofHours(1), sticknessPoint, false));
```

**Comment by vladimir-bukhtoyarov** [comment]
@siwhiting what do you think about the API proposed above?

**Comment by siwhiting** [comment]
The API looks good to me. I would suggest adding the examples to the documentation, as I found the firstRefillTime calculation really useful.

BTW, in the 4th example, the number of tokens is 266 (not 366)
i.e. (timeOfFirstRefill - now) / period * tokens 
     (40m/60m * 400 tokens) = 266 tokens

method could be renamed to something like Refill.intervallyAligned ?

**Comment by vladimir-bukhtoyarov** [comment]
> method could be renamed to something like Refill.intervallyAligned ?

Good, I like the 'intervallyAligned'.

According the 4th example. Pay attention that capacity is 400 in same time refill bounded to 100, numbers differ from each other, it is rarely used case(introduced in scope #13 ) . So I argue that rules for initial tokens calculation should be more complected:
```java
// sanity check
if (now >= timeOfFirstRefill) {
   return capacity;
}

if (capacity >= refillTokens) {
   // most likely case
   guaranteedBase = capacity - refillTokens;
} else {
   // very rare case, nobody uses library in such way in real life
   guaranteedBase = 0;
}
return Math.min(capacity, guaranteedBase + (timeOfFirstRefill - now)/refillPeriod * refillTokens)
```
Lets apply rules above to several examples
```java
        // first refill will happen in the beginning of next hour
        // imagine that wall clock is 16:20, the first refill will happen at 17:00
        Instant firstRefillTime = ZonedDateTime.now()
                .truncatedTo(ChronoUnit.HOURS)
                .plus(1, ChronoUnit.HOURS)
                .toInstant();

        // initial tokens 366 
        Bandwidth.classic(400, Refill.intervallyAligned(100, Duration.ofHours(1), firstRefillTime, true));
        // calculated by formula min(400, max(0, 400 - 100) +  40/60*100) = min(400, 300 + 66) = 366

       // initial tokens 333 
       Bandwidth.classic(400, Refill.intervallyAligned(200, Duration.ofHours(1), firstRefillTime, true));
       // calculated by formula min(400, max(0, 400 - 200) +  40/60*200) = min(400, 200 + 133) = 333

       // initial tokens 300 
       Bandwidth.classic(400, Refill.intervallyAligned(300, Duration.ofHours(1), firstRefillTime, true));
       // calculated by formula min(400, max(0, 400 - 300) +  40/60*300) = min(400, 100 + 200) = 300

       // initial tokens 266 
       Bandwidth.classic(400, Refill.intervallyAligned(400, Duration.ofHours(1), firstRefillTime, true));
       // calculated by formula min(400, max(0, 400 - 400) +  40/60*400) = min(400, 0 + 266) = 266
```
In a follow-up to examples above, I want to describe empirical rule: The amount of tokens which we should initially kick-out from a bucket directly depends on differences between bandwidth capacity and volume of the refill

**Comment by vladimir-bukhtoyarov** [comment]
@siwhiting if you have no objections according to math model then I am going to provide release candidate version on Monday.

**Comment by siwhiting** [comment]
I've no objections.

**Comment by vladimir-bukhtoyarov** [comment]
released under version 4.5.0

**Comment by vladimir-bukhtoyarov** [comment]
@marcosbarbero @MarcGiffing this feature can be interesting for you.

**Comment by marcosbarbero** [comment]
Hi @vladimir-bukhtoyarov thanks for the heads up! I'll certainly take a look on that :)
