### ISSUE TITLE
Concurrent processing issue with Redisson/Redis and Bucket4j 

### ISSUE THREAD

**Issue by saindavs** [vladimir-bukhtoyarov/bucket4j#104]
Hi Vladimir,

We are using bucket4j component for one of our API to throttle the request. The API that we wanted to throttle is running on 1 unix servers with 2 JVMs
When we have done a performance testing after enabling the throttling with bucket4j, we observed that the tokens are not being managed properly.

Ex: We have created a bucket with 50 tokens, and ran a performance test with Jmeter with 100 concurrent users and we see that more than 50 requests were served. Here the expected behavior it should serve only 50 requests as we have only 50 tokens on the bucket.

Also, We want to achieve the below scenario, is it possible through Bucket4j?

Assume, our Server is able to handle 1000 requests per minute. We have 2 partners to consume our API, so we have created 2 buckets with each 500 tokens. But, we would like to handle only 50 active concurrent threads/requests at a time even though we have enough tokens in that bucket.

We are using Redis as a db for managing the tokens and below maven dependencies

<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-core</artifactId>
			<version>4.4.1</version>
		</dependency>
		
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-jcache</artifactId>
			<version>4.4.1</version>
		</dependency>
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
		</dependency> 

Thank you in advance for your help. Could you please respond to this ASAP.

Regards,
Sudhakar

**Comment by saindavs** [comment]
Hi Vladimir,
Forgot to tell you that we are using Redis as a db for managing the tokens.

**Comment by saindavs** [comment]
We are using the below maven dependencies

<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-core</artifactId>
			<version>4.4.1</version>
		</dependency>
		
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-jcache</artifactId>
			<version>4.4.1</version>
		</dependency>
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
		</dependency>

**Comment by vladimir-bukhtoyarov** [comment]
Hello Sudhakar,

**According to the rate overflow:** 

-   Firstly, you should achieve an understanding of short time burst. You can do it by reading my documentation [Be wary of short-term bursts](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/production-generic-checklist.md#be-wary-of-short-term-bursts). In general case you can observe double rate for a very short time because it is a fundamental limitation of token/leaky bucket algorithm. So please provide the concrete value of rate that you observed, and how long you saw this rate.

- Secondly, I have no information if Redisson is a mature implementation of JCache or not(I suppose that not, but it is just my speculation). I am unable to test the compatibility of Bucket4j with all possible JCache implementations, but to make my users safe I created the strong test,  please run it with Redisoon [JCache provider concurrency isolation test](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/production-jcache-checklist.md#verification-of-compatibility-with-particular-jcache-provider-is-your-responsibility). If test will fail then contact Redisson developers directly and of course you should not use Bucket4j with Redisson if test fails.

**According to the limitation of concurrent threads:**
Bucket4j does not solve this kind of problems, but if you want solution which is suitable for distributed use case then I recommend to use distributed semaphore, each JCache provider typically provides this abstraction.

**Comment by saindavs** [comment]
Hi Vladimir,
Thank you so much for your reply on this.

I did a test to see whether the redisson is compatible with bucket4J. and got below error

Exception in thread "main" java.lang.IllegalStateException: Implementation which you use is not compatible with Bucket4j, 20 writes are missed
	at com.adp.autopay.aspect.RedissonCompatibilityTest.test(RedissonCompatibilityTest.java:68)
	at com.adp.autopay.aspect.RedissonCompatibilityTest.main(RedissonCompatibilityTest.java:85)


I have taken your test class and added redisson config to know whether it is compatible with bucket4J or not. Could you please confirm whether my class to test is correct?

Please find the source code as below

package com.adp.autopay.aspect;
import java.io.File;
import java.io.Serializable;
import java.net.URI;
import java.util.concurrent.CountDownLatch;

import javax.cache.Cache;
import javax.cache.CacheManager;
import javax.cache.Caching;
import javax.cache.configuration.CompleteConfiguration;
import javax.cache.configuration.MutableConfiguration;
import javax.cache.processor.EntryProcessor;
import javax.cache.spi.CachingProvider;

public class RedissonCompatibilityTest {

	private static URI DEFAULT_URI;

	static {

		try {
			DEFAULT_URI = new File("/opt/jass/appresources/turbopayrolloutput/bin/redisson-jcache.yaml").toURI();
		} catch (Exception e) {
			e.printStackTrace();

		}
	}

	final Cache<String, Integer> cache;

	public RedissonCompatibilityTest(Cache<String, Integer> cache) {
		this.cache = cache;
	}

	public void test() throws InterruptedException {
		System.out.println("started test method!");
		String key = "42";
		int threads = 2;
		int iterations = 20;
		cache.put(key, 0);
		CountDownLatch latch = new CountDownLatch(threads);
		for (int i = 0; i < threads; i++) {
			new Thread(() -> {
				try {
					for (int j = 0; j < iterations; j++) {
						EntryProcessor<String, Integer, Void> processor = (EntryProcessor<String, Integer, Void> & Serializable) (
								mutableEntry, objects) -> {
							int value = mutableEntry.getValue();
							mutableEntry.setValue(value + 1);
							return null;
						};
						System.out.println(Thread.currentThread().getName() + " Invoking with key: " + key
								+ " processor: " + processor);
						cache.invoke(key, processor);
					}
				} finally {
					latch.countDown();
				}
			}).start();
		}
		latch.await();
		int value = cache.get(key);
		if (value == threads * iterations) {
			System.out.println("Implementation which you use is compatible with Bucket4j");
		} else {
			String msg = "Implementation which you use is not compatible with Bucket4j";
			msg += ", " + (threads * iterations - value) + " writes are missed";
			throw new IllegalStateException(msg);
		}
	}

	public static void main(String args[]) throws InterruptedException {
		System.out.println("started main method!");
		CompleteConfiguration<String, Integer> config = new MutableConfiguration<String, Integer>()
				.setTypes(String.class, Integer.class);
		CachingProvider cachingProvider = Caching.getCachingProvider();
		CacheManager cacheManager = cachingProvider.getCacheManager(DEFAULT_URI,
				cachingProvider.getDefaultClassLoader());
		Cache<String, Integer> cache = cacheManager.createCache("rate-demo4", config);
		// ProxyManager<String> pManager =
		// Bucket4j.extension(JCache.class).proxyManagerForCache(cache);

		RedissonCompatibilityTest t1 = new RedissonCompatibilityTest(cache);

		t1.test();

	}

}




I have also downloaded the hazelcast and did a test to know whether it is compatible with bucket4J or not. I got message saying "Implementation which you use is compatible with Bucket4j"
Could you please confirm if the below code is right ?


package com.adp.autopay.aspect;

import java.io.Serializable;
import java.util.Map;
import java.util.Queue;
import java.util.concurrent.CountDownLatch;

import javax.cache.Cache;
import javax.cache.processor.EntryProcessor;

import com.hazelcast.cache.ICache;
import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.ICacheManager;

public class HazelcastCompatibilityTest {

	final Cache<String, Integer> cache;

	public HazelcastCompatibilityTest(Cache<String, Integer> cache) {
		this.cache = cache;
	}

	public void test() throws InterruptedException {
		System.out.println("started test method!");
		String key = "42";
		int threads = 4;
		int iterations = 1000;
		cache.put(key, 0);
		CountDownLatch latch = new CountDownLatch(threads);
		for (int i = 0; i < threads; i++) {
			new Thread(() -> {
				try {
					for (int j = 0; j < iterations; j++) {
						EntryProcessor<String, Integer, Void> processor = (EntryProcessor<String, Integer, Void> & Serializable) (
								mutableEntry, objects) -> {
							int value = mutableEntry.getValue();
							mutableEntry.setValue(value + 1);
							return null;
						};
						System.out.println(Thread.currentThread().getName() + " Invoking with key: " + key
								+ " processor: " + processor);
						cache.invoke(key, processor);
					}
				} finally {
					latch.countDown();
				}
			}).start();
		}
		latch.await();
		int value = cache.get(key);
		if (value == threads * iterations) {
			System.out.println("Implementation which you use is compatible with Bucket4j");
		} else {
			String msg = "Implementation which you use is not compatible with Bucket4j";
			msg += ", " + (threads * iterations - value) + " writes are missed";
			throw new IllegalStateException(msg);
		}
	}

	public static void main(String args[]) throws InterruptedException {
		System.out.println("started main method!");

		Config config = new Config();
		config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
		config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true).clear().addMember("29.160.10.93");

		MemoryAllocatorType allocatorType = MemoryAllocatorType.STANDARD;
		config.getNativeMemoryConfig().setEnabled(true).setAllocatorType(allocatorType)
				.setSize(new MemorySize(1, MemoryUnit.GIGABYTES));

		config.getCacheConfig("Arush1").setInMemoryFormat(InMemoryFormat.BINARY).setEvictionConfig(new EvictionConfig(
				99, EvictionConfig.MaxSizePolicy.ENTRY_COUNT, EvictionConfig.DEFAULT_EVICTION_POLICY));

		final HazelcastInstance hz1 = Hazelcast.newHazelcastInstance(config);
		ICacheManager cacheManager = hz1.getCacheManager();
		ICache<String, Integer> cache = cacheManager.getCache("Arush1");
		HazelcastCompatibilityTest t1 = new HazelcastCompatibilityTest(cache);
		t1.test();

	}

}


Thank you for your help Vladimir, much appreciated. Please advise me if the above code is not correct.

Regards,
Sudhakar

**Comment by vladimir-bukhtoyarov** [comment]
Both tests for Redisson and Hazelcast look correct. Exception about missed writes for Redisson explicitly describes the problem with missed writes, so you should not use Bucket4j with JCache over Reddison. 

But if you want to use Bucket4j with Redisson that there is a way to do it with Bucket4j ```5.0.0```. This version is not released yet, but I have an alpha release(which is technically stable but documentation is not written yet)  

5.0.0-alpha-2019-10-18
```xml
<dependency>
    <groupId>com.github.vladimir-bukhtoyarov</groupId>
    <artifactId>bucket4j-core</artifactId>
    <version>5.0.0-alpha-2019-10-18</version>
</dependency>
```
Because it is early version, I will not deploy it to Maven Central. But it is available through JCenter
```
<repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
</repositories>
```

To implement own integration for Redisson you can use following example https://github.com/vladimir-bukhtoyarov/bucket4j/tree/5.0/bucket4j-examples/src/test/java/example/distributed/generic/redisson/rmap_cas Where:

- [RMapBasedRedissonBackend](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/5.0/bucket4j-examples/src/test/java/example/distributed/generic/redisson/rmap_cas/RMapBasedRedissonBackend.java) is example of backend on top of Redisson.
- [RMAP_Redisson_Example.](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/5.0/bucket4j-examples/src/test/java/example/distributed/generic/redisson/rmap_cas/RMAP_Redisson_Example.java) is example of usage for RMapBasedRedissonBackend.

**Comment by vladimir-bukhtoyarov** [comment]
@saindavs about your Jmeter tests. In order to help I need to view the code of bucket initialization and the code of tokens consumption.

**Comment by saindavs** [comment]
Good Morning Vladimir,
Here is the details on how we are initializing the bucket and consuming the tokens.
1. We have around 30 applications and 10 partners how consumes our API to which we have to enable the throttling.
2. So, we have created and Web App called throttleManager. From this application, the authorized users can come and create/update the bucket based on the usage for a particular partner of an API. The bucket configuration stored in Redis.
3. We have another component called throttlingUtils. It is a maven dependency, any API which wanted throttling has to have a throttlingUtils as a maven dependency in their API. In other words, The code to consume the tokens exist at each and every API.

Here is the code to create/update/delete the bucket from throttlingManager

Config class
--------------
@Bean
	@DependsOn("redisson")
	public Cache<String, GridBucketState> getCache() {

		CompleteConfiguration<String, GridBucketState> config = new MutableConfiguration<String, GridBucketState>()
				.setTypes(String.class, GridBucketState.class);
		CachingProvider cachingProvider = Caching.getCachingProvider();
		CacheManager cacheManager = cachingProvider.getCacheManager(DEFAULT_URI, cachingProvider.getDefaultClassLoader());
		Cache<String, GridBucketState> cache = cacheManager.createCache("rate-limit-cache", config);
		//ProxyManager<String> pManager = Bucket4j.extension(JCache.class).proxyManagerForCache(cache);
		return cache;

class to create/update buckets
-------------------------------------
@Service("bucketConfigurationService")
public class BucketConfigurationServiceImpl implements BucketConfigurationService {

	private static final Logger logger = LoggerFactory.getLogger(BucketConfigurationServiceImpl.class);

	@Autowired
	Cache<String, GridBucketState> cache;

	private ProxyManager<String> pManager;

	@Override
	public void createOrReplaceBucketwithUpdatedConfig(String productID, RBucket<ThrottleManagerDto> bucketConfig,
			ThrottleManagerDto throttleManagerDto) {
		Bucket bucket = null;

		try {
			BucketConfiguration newConfiguration = getBucketConfiguration(throttleManagerDto);
			Optional<Bucket> bucket1 = getProxyManager().getProxy(productID);
			Optional<BucketConfiguration> bucketCon = getProxyManager().getProxyConfiguration(productID);

			if (bucketCon.isPresent() && bucket1.isPresent()) {
				bucket = bucket1.get();
				bucketCon.get().checkCompatibility(newConfiguration);
				bucket.replaceConfiguration(newConfiguration);
				logger.info("Bucket configuration replaced for product: " + productID + ". New Bucket Configuration: "
						+ newConfiguration);
				throttleManagerDto.setThrottleUpdated(true);
			} else {
				bucket = getProxyManager().getProxy(productID, newConfiguration);
				bucket.replaceConfiguration(newConfiguration);
				logger.info("New Bucket created for product: " + productID + ". New Bucket Configuration: "
						+ newConfiguration);
				throttleManagerDto.setThrottleUpdated(true);
			}

		} catch (IncompatibleConfigurationException ex) {
			logger.error("New bucket configuration is incompatibale for product: " + productID);
			throw ex;
		}

	}

	private BucketConfiguration getBucketConfiguration(ThrottleManagerDto throttlConfig) {
		BucketConfiguration configuration = null;
		Refill refill = null;

		if (StringUtils.isBlank(throttlConfig.getRefillType())
				|| throttlConfig.getRefillType().equalsIgnoreCase("interval")) {
			refill = Refill.intervally(Long.parseLong(throttlConfig.getRefillTokens()),
					Duration.ofMinutes(Integer.parseInt(throttlConfig.getInterval())));
		} else {

			refill = Refill.greedy(Long.parseLong(throttlConfig.getRefillTokens()),
					Duration.ofMinutes(Integer.parseInt(throttlConfig.getInterval())));

		}
		Bandwidth limit = Bandwidth.classic(Long.parseLong(throttlConfig.getMaxTokens()), refill);
		limit = limit.withInitialTokens(Long.parseLong(throttlConfig.getInitialTokens()));
		configuration = Bucket4j.configurationBuilder().addLimit(limit).build();
		return configuration;

	}

	@Override
	public void disableThrottling(String productID, RBucket<ThrottleManagerDto> bucketConfig,
			ThrottleManagerDto throttleManagerDto) {

		Optional<Bucket> bucket1 = getProxyManager().getProxy(productID);
		if (bucket1.isPresent()) {
			cache.remove(productID);
			throttleManagerDto.setThrottleUpdated(true);
			logger.info("Disable Throttling..,bucket configuration removed for product: " + productID);
		} else {
			logger.error("bucket configuration not found for product: " + productID);
			throw new NotFoundException("bucket configuration not found for product: " + productID);
		}

	}

	@Override
	public BucketDataDto getBucketInformation(String bucketId, String noOfTokens) {
		Bucket bucket = null;
		BucketConfiguration bucketCon = null;
		BucketDataDto bucketdata = new BucketDataDto();
		double waitingTime;
		Optional<Bucket> bucket1 = getProxyManager().getProxy(bucketId);
		Optional<BucketConfiguration> bucketCon1 = getProxyManager().getProxyConfiguration(bucketId);
		if (bucket1.isPresent() && bucketCon1.isPresent()) {
			bucket = bucket1.get();
			bucketCon = bucketCon1.get();
			bucketdata.setAvailableTokens(bucket.getAvailableTokens());
			if (StringUtils.isBlank(noOfTokens)) {
				waitingTime = bucket.estimateAbilityToConsume(1).getNanosToWaitForRefill();
			} else {
				waitingTime = bucket.estimateAbilityToConsume(Integer.parseInt(noOfTokens)).getNanosToWaitForRefill();
			}
			if (bucket.getAvailableTokens() > 0 && StringUtils.isBlank(noOfTokens)) {
				long tokens = bucket.getAvailableTokens() + 1;
				waitingTime = bucket.estimateAbilityToConsume(tokens).getNanosToWaitForRefill();
			}
			// Converting waiting time from nano secs to mins.
			bucketdata.setTimetoRefill(formatTimetoMinutes(waitingTime));

			Bandwidth bandwidth = bucketCon.getBandwidths()[0];
			bucketdata.setBandwidth(null != bandwidth ? bandwidth.toString() : "Not found");
			if (null != bandwidth && StringUtils.isNotBlank(bandwidth.toString())) {
				setBandwidthData(bandwidth.toString(), bucketdata);
			}
			logger.info("Bucket configuartion for product " + bucketId + " is : " + bandwidth.toString());

		} else {
			throw new NotFoundException("bucket  not found for Id: " + bucketId);
		}
		return bucketdata;

	}

	private void setBandwidthData(String bandwidth, BucketDataDto bucketdata) {
		try {

			bandwidth = bandwidth.replace("Bandwidth", "").replace("{", "").replace("}", "");
			String[] config = bandwidth.split(",");

			for (int i = 0; i < config.length; i++) {
				config[i] = config[i].split("=")[1];

			}

			bucketdata.setMaxTokens(Long.valueOf((config[0])));
			bucketdata.setInitialTokens(Long.valueOf(config[1]));
			bucketdata.setRefillPeriod(formatTimetoMinutes(Double.valueOf(config[2])));
			bucketdata.setRefillTokens(Long.valueOf(config[3]));
			bucketdata.setRefillIntervally(Boolean.valueOf(config[4]));
		} catch (Exception e) {
			logger.error("Exception while fetching bandwidth data..");
			throw e;
		}

	}

	private String formatTimetoMinutes(double waitingTime) {
		String formatTime = null;
		waitingTime = (waitingTime / (1e9 * 60));
		DecimalFormat df = new DecimalFormat("#.###");
		df.setRoundingMode(RoundingMode.CEILING);
		formatTime = df.format(waitingTime);
		return formatTime;

	}

	public ProxyManager<String> getProxyManager() {
		if (null == pManager) {
			pManager = Bucket4j.extension(JCache.class).proxyManagerForCache(cache);
		}
		return pManager;
	}

	
}

Here is the code to consume the tokens from the throttlingUtils

@Aspect
@Component
public class ThrottleRequestAspect {

	private static final Logger logger = LoggerFactory.getLogger(ThrottleRequestAspect.class.getName());
	public static final String TURBO_API = "turbo";
	public static final String CONSUMER_APP_GUID = "consumerAppGuid";

	@Autowired
	private ProxyManager<String> pManager;

	// @Autowired
	/* private RedissonClient rClient; */

	@Before("execution(* com.abc.xyz.company.controller.*.*(..))")
	
	public void throttleRequest() throws Exception {

		Instant begin1 = Instant.now();
		HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.currentRequestAttributes())
				.getRequest();
		String sessionId = request.getHeader("sm_serversessionid");
		MDC.put("sessionId", sessionId);
		String uri = request.getRequestURI().toString();
		MDC.put("uri", uri);
		String productID = getProductKey(uri);
		String clientId = (String) MDC.get(CONSUMER_APP_GUID);

		// Client id set in oauth2 filter.
		clientId = (String) MDC.get(CONSUMER_APP_GUID);
		if (StringUtils.isNotBlank(clientId)) {
			productID = productID.concat(":").concat(clientId);
		} else if (StringUtils.isNotBlank(sessionId)) {
			productID = productID.concat(":").concat(sessionId);
		} else {
			logger.error("Product key not found in the request ..Processing request without throttling..");
			return;
		}

		try {
			Bucket bucket = null;
			Instant begin = Instant.now();

			try {
				bucket = getBucketFromRedis(productID);
			} catch (Exception e) {
				logger.error("Exception occured while connecting to redis client for product " + productID
						+ ". Serving request by skipping throttle mechanism..");
				return;
			}

			if (null == bucket) {
				logger.info("Bucket information not found for the product : " + productID
						+ " Throttling cannot be enabled for this product.");
				return;
			}

			logger.info("Tokens available for product " + sessionId + ":  " + bucket.getAvailableTokens());

			Instant end = Instant.now();
			logger.info("Time taken to get bucket information from Redis: " + Duration.between(begin, end).toMillis()
					+ " ms.");

			consumeToken(sessionId, bucket);

		} catch (Exception ex) {
			if (!(ex instanceof HttpClientErrorException)) {
				logger.error("Exception occured in throttling Turbo API for product: " + sessionId + " Exception : "
						+ ex.getMessage());
				ex.printStackTrace();
			}
			throw ex;
		}
		Instant end1 = Instant.now();
		logger.info(
				"Total time taken for Throttling the request : " + Duration.between(begin1, end1).toMillis() + " ms.");

	}

	private String getProductKey(String uri) {
		String productKey = null;
		if (uri != null) {
			uri = uri.toLowerCase(Locale.ENGLISH);
			for (String api : ThrottlingUtil.apiKeyMap.keySet()) {
				if (uri.contains(api.toLowerCase(Locale.ENGLISH))) {
					String key = ThrottlingUtil.apiKeyMap.get(api);
					productKey = ThrottlingUtil.keyRequestIdMap.get(key);
					break;
				}
			}
		}
		return productKey;
	}

	private void consumeToken(String sessionId, Bucket bucket) {
		Instant begin = Instant.now();
		// tryConsume returns false immediately if no tokens available with the bucket
		if (!bucket.tryConsume(1)) {
			long waitingTime = bucket.estimateAbilityToConsume(1).getNanosToWaitForRefill();
			waitingTime = waitingTime / 1000000000;
			throw new HttpClientErrorException(HttpStatus.TOO_MANY_REQUESTS, "Too Many Requests for Product "
					+ sessionId + ". Requests will be served after " + waitingTime + " seconds.", null, null, null);
		}

		Instant end = Instant.now();
		logger.info("Time taken for consuming bucket token " + Duration.between(begin, end).toMillis() + " ms.");
	}

	/*
	 * private void getThrottleVoFromRedis(String productID) {
	 * RBucket<ThrottleManagerDto> bucketConfig = null; ThrottleManagerDto
	 * throttleManagerDto = null;
	 * 
	 * try { bucketConfig = rClient.getBucket(productID); throttleManagerDto =
	 * bucketConfig.get(); } catch (Exception e) { logger.
	 * error("Exception occured while connecting to redis client for product " +
	 * productID + ". Serving request by skipping throttle mechanism..");
	 * e.printStackTrace(); return; } }
	 * 
	 * private Bucket replaceBucketwithUpdatedConfig(String productID,
	 * RBucket<ThrottleManagerDto> bucketConfig, ThrottleManagerDto
	 * throttleManagerDto) { Bucket bucket = null; try { BucketConfiguration
	 * newConfiguration = getBucketConfiguration(throttleManagerDto); bucket =
	 * pManager.getProxy(productID, newConfiguration); Optional<BucketConfiguration>
	 * bucketCon = pManager.getProxyConfiguration(productID); if
	 * (bucketCon.isPresent()) {
	 * bucketCon.get().checkCompatibility(newConfiguration);
	 * bucket.replaceConfiguration(newConfiguration);
	 * throttleManagerDto.setThrottleUpdated(false);
	 * bucketConfig.set(throttleManagerDto); } } catch
	 * (IncompatibleConfigurationException ex) {
	 * logger.error("New bucket configuration is incompatibale for product: " +
	 * productID); throw ex; }
	 * 
	 * logger.error("Bucket configuration updated for the product : " + productID +
	 * "  New bucket configuration : " + throttleManagerDto.toString()); return
	 * bucket; }
	 * 
	 * private BucketConfiguration getBucketConfiguration(ThrottleManagerDto
	 * throttlConfig) {
	 * 
	 * Refill refill = Refill.intervally(Long.parseLong(throttlConfig.getTokens()),
	 * Duration.ofMinutes(Integer.parseInt(throttlConfig.getInterval()))); Bandwidth
	 * limit = Bandwidth.classic(Long.parseLong(throttlConfig.getTokens()), refill);
	 * BucketConfiguration configuration =
	 * Bucket4j.configurationBuilder().addLimit(limit).build(); return
	 * configuration;
	 * 
	 * }
	 */

	private Bucket getBucketFromRedis(String bucketKey) {
		Bucket bucket = null;
		try {

			Optional<Bucket> buck = pManager.getProxy(bucketKey);
			if (buck.isPresent()) {
				bucket = buck.get();
			} else {
				logger.info("Throttling Bucket not found for the product: " + bucketKey
						+ ". Throttling is skipped for this product.");
			}

		} catch (Exception ex) {
			ex.printStackTrace();
		}

		return bucket;
	}

}

It seems the hazel cast is not suitable in our case because, it is asking us to provide the IP address to form the cluster from the JVMS, as our applications are there in docker and IP address will keep on change

As you suggested we can use the Redisson with bucket4j 5. We need to achieve the below requirements

1. Throttle at concurrent requests; Ex: We should serve only 20 live/parallel/concurrent requests even though we have tokens in the bucket. 

When is the official release for bucket4j 5? can the bucket4j 5 provides the above requirement?


Regards,
Sudhakar

**Comment by vladimir-bukhtoyarov** [comment]
Hello @Sudhakar

Unfortunately, Bucket4j does not provide functionality for distributed semaphores, and will never provide this kind of functionality in the future. Since you already use Redis try to use [PermitExpirableSemaphore](https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers#87-permitexpirablesemaphore) from Redisson library.

```java
if (bucket.tryConsume(1)) {
   try {
     semaphore.lock();
     doSumStaff();
   } finally {
     semaphore.unlock(); 
   }
}
```

According to official release of 5.0 branch - I plan to do it in February 2020.

**Comment by freakynit** [comment]
I have observed similar behavior. Bucket4J doesn't seem to work correctly in distributed usage. 

When I run single instance of load-test client (see gist below) using `redisson jcache` implementation, everything works as expected. But, the moment I switch to using more than one concurrent load-test clients, the results are not as expected. 

Expected result was that each client would see reduced number of available tokens, in exact (or at least close enough) ratios of running clients. But, results seem to completely ignore the distributed nature of usage and behave as if each client has as many tokens available.

I have prepared sample code here: https://gist.github.com/freakynit/10b30a6571322556189e017867d11ea4

The problem (at least according to me) seem to be this Q/A:
> Question: is the provided JCache integration safe across multiple JVMs? Does it ensure that two nodes creating a bucket simultaneously on a given Cache<K, V> will only actually create one single bucket (without resetting a previously created one with the same key)?
Answer: Yes. JCache integration is safe for multi node environment, Bucket4j never replaces bucket which already exists. This behavior is guaranteed by putIfAbsent method contract of javax.cache.Cache class.

My question is, is this behavior expected, and hence, bucket4j doesn't support distributed use-case, or, my usage of library is wrong.

**Comment by vladimir-bukhtoyarov** [comment]
@freakynit Bucket4j works correctly in distributed use case, it was tested many times by many people. But you should follow [this instruction](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/production-jcache-checklist.md#verification-of-compatibility-with-particular-jcache-provider-is-your-responsibility) in order to check if underlying jcache provider provides or not strong concurrency isolation. If JCache provider which you are trying to use is unable to provide execution of EntryProcessor in isolation then Bucket4j is unable to help because of fundamental limitation of underplayed technology.

Anyway there is a way of correct usage of Bucket4j with Redisson described in the [comment above](https://github.com/vladimir-bukhtoyarov/bucket4j/issues/104#issuecomment-547016680)

**Comment by freakynit** [comment]
Thanks @vladimir-bukhtoyarov . I did run compatibility test as mentioned by you with redisson-jcache backend. 

Unfortunately, this test came out negative. Meaning, redisson-jcache implementation does not currently provide full spec-compliant jcache implementation (tested with redisson version: 3.11.6) .

Here's the final output of test: 
`Exception in thread "main" java.lang.IllegalStateException: Implementation which you use is not compatible with Bucket4j, 2769 writes are missed`

**Comment by vladimir-bukhtoyarov** [comment]
Closed as third-party issue

**Comment by saindavs** [comment]
@vladimir-bukhtoyarov 

I could not download the below bucket4j 5.0.0 from jcenter. could you please let me know is the jar uploaded?

<dependency>
    <groupId>com.github.vladimir-bukhtoyarov</groupId>
    <artifactId>bucket4j-core</artifactId>
    <version>5.0.0-alpha-2019-10-18</version>
</dependency>
Because it is early version, I will not deploy it to Maven Central. But it is available through JCenter

<repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
</repositories>

**Comment by victoraldir** [comment]
@saindavs It's been released today right here. 

Please, find @vladimir-bukhtoyarov  about this WIP

> Keep in mind that writing javadocs for 5.0.0 is in progress #69
> The same for wiki pages which are obsolete because 5.0.0 branch has been refactored significantly especially in the context of distributed usage

https://search.maven.org/artifact/com.github.vladimir-bukhtoyarov/bucket4j-core/5.0.0-beta.01-09-2020/jar

**Comment by jonathannaguin** [comment]
@vladimir-bukhtoyarov do you think this will be released soon?

**Comment by shivam2146** [comment]
@vladimir-bukhtoyarov With newer versions of bucket4j we have bucket4j-redis which provides a RedissonBasedProxyManager based bucket usage. Is that one safe to use in a distributed env? is that one safe to use where multiple instances will concurrently access the same bucket?

Also, I cannot find any example how to use it. Can you please help me out with some reference or example. bit new with bucket4j.

would below code be correct way to use it?

```
// create Redisson client
Config config = new Config();
config.useSingleServer().setAddress("redis://<host>:6379");
RedissonClient redissonClient = Redisson.create(config);

// create RedissonBasedProxyManager using CommandExecutor
CommandExecutor commandExecutor = new RedissonExecutorService(redissonClient);
RedissonBasedProxyManager proxyManager = RedissonBasedProxyManager.builderFor(commandExecutor)
        .withExpirationStrategy(ExpirationAfterAccessStrategy.forLastAccess(Duration.ofMinutes(5)))
        .build();

Refill refill =
        Refill.intervally(
            100,
            Duration.ofSeconds(60));

// create BucketConfiguration
BucketConfiguration configuration = BucketConfiguration.builder()
        .addLimit(Bandwidth.classic(100, refill))
        .build();

// create Bucket using proxyManager
Bucket bucket = proxyManager.builder().build("my-bucket", configuration);
```

**Comment by vladimir-bukhtoyarov** [comment]
Hello @freakynit 

> Is that one safe to use in a distributed env?

Yes, it is safe.

> Also, I cannot find any example how to use it. Can you please help me out with some reference or example. bit new with bucket4j.

Try to look to examples related to another extentions in [reference](https://bucket4j.com/8.2.0/toc.html) and [third-party articles](https://bucket4j.com/#third-party-articles), then do the same just with Redisson.

**Comment by shivam2146** [comment]
Thanks @vladimir-bukhtoyarov !!
