### ISSUE TITLE
Latest version (4.5.0) is not available as a Maven dependency

### ISSUE THREAD

**Issue by basalphenaar** [vladimir-bukhtoyarov/bucket4j#105]
I noticed that the latest version of bucket4j (4.5.0) is not available as a Maven dependency: https://mvnrepository.com/artifact/com.github.vladimir-bukhtoyarov/bucket4j-core

The latest available version is 4.4.1, however this release doesn't seem to be mentioned on the releases page here (only 4.4.0 and 4.5.0 are there).

Is it possible to release v4.5.0 so that it can be used as a Maven dependency? Thanks for making a great library by the way!

**Comment by vladimir-bukhtoyarov** [comment]
@basalphenaar yes, looks like I forgot to sync JCenter and maven Central for release 4.5.0. I will synchronize tommorrow. If you are unable to wait then just use artifacts from [JCenter](https://bintray.com/vladimir-bukhtoyarov/maven/bucket4j-parent/4.5.0#files/com/github/vladimir-bukhtoyarov)
```xml
<repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
</repositories>
```

**Comment by basalphenaar** [comment]
@vladimir-bukhtoyarov Thanks for your quick response! I'm not in a real hurry to use the latest version, I'll wait until the sync is done, thanks in advance.

**Comment by vladimir-bukhtoyarov** [comment]
synced
