### ISSUE TITLE
Add JDK 9+ / modules support

### ISSUE THREAD

**Issue by skjolber** [vladimir-bukhtoyarov/bucket4j#106]
Please add an [Automatic-Module-Name](https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers) entry in the manifest, or full modules support, so that this library deterministicly can be used as an dependency in a JDK 9+ project.

**Comment by vladimir-bukhtoyarov** [comment]
Looks reasonable. I will add "Automatic-Module-Name" to the manifests at the weekend.

**Comment by vladimir-bukhtoyarov** [comment]
released under version 4.6.0
