### ISSUE TITLE
No Javadoc for GridProxy

### ISSUE THREAD

**Issue by jameskleeh** [vladimir-bukhtoyarov/bucket4j#112]
I'm trying to create my own implementation of GridProxy to delegate operations to a generic cache interface that supports many providers (hazelcast, etc). That requires me to implement GridProxy however there is no javadoc to describe how the methods should behave.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @jameskleeh 

GridProxy is internal part of library which is not visible for public API. I do now want to document it by many reasons. Anyway you can find out required behavior by investigation any working extension, for example [Bucket4j-Hazelcast](https://github.com/vladimir-bukhtoyarov/bucket4j/tree/4.7/bucket4j-hazelcast/src/main/java/io/github/bucket4j/grid/hazelcast). But pay attention that in upcoming ```5.0`` release distributed extensions for Bucket4j has been rewritten, so it is better to make your own extensions based on [5.0 branch](https://github.com/vladimir-bukhtoyarov/bucket4j/tree/5.0/bucket4j-hazelcast/src/main/java/io/github/bucket4j/grid/hazelcast)
