### ISSUE TITLE
Advanced Usage example is missing method definition

### ISSUE THREAD

**Issue by forsethc** [vladimir-bukhtoyarov/bucket4j#126]
Reading through the Advanced Usage docs ([here](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/advanced-usage.md#using-the-verboseresult-api)) regarding using the `VerboseResult` to compute bucket capacity, the docs reference a `computeCapacity` method that takes in a `BucketConfiguration`.

There doesn't appear to be any documentation on how to implement something that would compute the capacity of the bucket nor an example implementation of the `computeCapacity` method referenced in the docs.

**Comment by vladimir-bukhtoyarov** [comment]
I have added more precise example

**Comment by forsethc** [comment]
Perfect, thanks for the quick response!
