### ISSUE TITLE
I can request over maximum rate limit

### ISSUE THREAD

**Issue by maetinee** [vladimir-bukhtoyarov/bucket4j#128]
I set rate limit 5 request / 1 min

but sometime I can sent request over maximum rate.

I log available tokens of bucket and I look something wrong.
Sometime (I wait 5 sec before 1 request) when pass 30sec avaliable token reset to 5 request but 
I fix 

```
Refill.intervally(5, Duration.ofSeconds(60)) (wait for timeout reset avaliable token)
Bandwidth.classic(5,Refill.intervally(5, Duration.ofSeconds(60)))
```

Issue is how can I fix this issue because avaliable token of bucket should be reset when pass 1 min.

I use bucket-core and bucket4j-jcache version 4.0.1

This is some part of my log. I start first request is 15:11:39 avaliable is 5 and the last request is 15.12.08 (pass after first request 29 sec) but avaliable token is 5.

```
RateLimitingFilter  : available: 5 time: 15:11:39.563
RateLimitingFilter  : ########################################
RateLimitingFilter  : available: 4 time: 15:11:46.840
RateLimitingFilter  : ########################################
RateLimitingFilter  : available: 3 time: 15:11:53.820
RateLimitingFilter  : ########################################
RateLimitingFilter  : available: 2 time: 15:12:01.482
RateLimitingFilter  : ########################################
RateLimitingFilter  : available: 5 time: 15:12:08.235
RateLimitingFilter  : ########################################
```

**Comment by vladimir-bukhtoyarov** [comment]
Hello @maetinee 

Please provide a self-executable example of the problem.

**Comment by maetinee** [comment]
first round request 3 request (5sec send 1 request) and wait for timeout.

**Comment by vladimir-bukhtoyarov** [comment]
@maetinee provided information is not helpful enough for diagnosing. I need to view(and run) **the code**.  

You can start from ignoring JCache(and particular vendor) at all by using just a local bucket and mock clock. For example:
```java
package io.github.bucket4j;

import java.time.Duration;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong;

public class X {

    public static void main(String[] args) {
        AtomicLong currentTimeNanos = new AtomicLong();

        TimeMeter ticker = new TimeMeter() {
            @Override
            public long currentTimeNanos() {
                return currentTimeNanos.get();
            }

            @Override
            public boolean isWallClockBased() {
                return true;
            }
        };

        Bucket bucket = Bucket4j.builder()
                .addLimit(Bandwidth.classic(5, Refill.intervally(5, Duration.ofSeconds(60))))
                .build();

        currentTimeNanos.set(TimeUnit.SECONDS.toNanos(7));
        bucket.tryConsume(1);
        System.out.println(TimeUnit.NANOSECONDS.toSeconds(currentTimeNanos.get()) + " - " +  
        bucket.getAvailableTokens());

        currentTimeNanos.set(TimeUnit.SECONDS.toNanos(14));
        bucket.tryConsume(1);
        System.out.println(TimeUnit.NANOSECONDS.toSeconds(currentTimeNanos.get()) + " - " +  
        bucket.getAvailableTokens());

        currentTimeNanos.set(TimeUnit.SECONDS.toNanos(21));
        bucket.tryConsume(1);
        System.out.println(TimeUnit.NANOSECONDS.toSeconds(currentTimeNanos.get()) + " - " +  
        bucket.getAvailableTokens());

        currentTimeNanos.set(TimeUnit.SECONDS.toNanos(28));
        bucket.tryConsume(1);
        System.out.println(TimeUnit.NANOSECONDS.toSeconds(currentTimeNanos.get()) + " - " +  
        bucket.getAvailableTokens());

        currentTimeNanos.set(TimeUnit.SECONDS.toNanos(35));
        bucket.tryConsume(1);
        System.out.println(TimeUnit.NANOSECONDS.toSeconds(currentTimeNanos.get()) + " - " +  
        bucket.getAvailableTokens());
    }

}

```

If you can not reproduce the problem via mocks but can reproduce via real code then provide it. Most likely in this case issue is related to JCache implementation vendor, anyway without a self-executable example I will not be able to help/

**Comment by maetinee** [comment]
ok thank

**Comment by maetinee** [comment]
@vladimir-bukhtoyarov I will try mock this proble and I cand reproduce via mocks.

**Comment by vladimir-bukhtoyarov** [comment]
@maetinee  at the timepoint **100** lastRefillTime was set to **60** independently from the fact that it was passed 80 seconds between interactions. This is how Refill.intervally was designed to behave, in your example, you always have a fixed time window between refill 60, 120, 180, 240, 300, etc. So refilling up to 5 tokens at the time point **120** is legal according to the math model. If I understand correctly you were expected that the refill timepoints sequence should be reset because of long inactivity interval (between 20 and 100 has passed 80 seconds). 

**Let me describe why current behavior is correct:**
The token-bucket can be described as following:
* **N** tokens are added to the bucket every **M** seconds.
* The bucket can hold at the most **C** tokens. If a token arrives when the bucket is full, it is discarded.
When you create ```Refill.intervally(5, Duration.ofSeconds(60))``` at the moment of time **T** you get the bucket which tries to refill tokens in the following sequence **T+60**,**T+120**,**T+180**,**T+240**, etc. Of course, because of the performance penalty, under the hood, there is no background thread that does this, but Bucket4j just emulates it. So there is no bug, Bucket4j works according to its math model.

**Comment by vladimir-bukhtoyarov** [comment]
But if you still required in resetting the refill sequence after a long inactivity period then I can extend the intervally refill, in the way something like the following:
```java
public static Refill intervally(long tokens, Duration period, boolean resetRefillSequenceAfterLongInactivityPeriod) {
        ...
}
```
I will be able to release it at weekends under the version **4.11**

**Comment by maetinee** [comment]
@vladimir-bukhtoyarov thank you so mush

**Comment by maetinee** [comment]
@vladimir-bukhtoyarov sorry, I don't sure about concept of this bucket.
You mean after first request token will be reset when sec are 60,120,180,240 right.

**Comment by vladimir-bukhtoyarov** [comment]
To be more accurate: there is no resetting. There is a continuous refill that can be treated as a background process.

**Comment by ykalayy** [comment]
I am confused also about how bandwidth works. I created a very very simple bucket. Which accepts 3 requests every 60 seconds. But with this bucket, I am able to consume 5 times the bucket in 50 sec.
Here is the sample reproduces code:
``
    Bucket bucket = Bucket4j.builder().addLimit(Bandwidth.simple(3, Duration.ofSeconds(60))).build();
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1));
        Thread.sleep(10000);
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1));
        Thread.sleep(10000);
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1));
        Thread.sleep(10000);
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1)); // <-
        Thread.sleep(10000);
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1));
        Thread.sleep(10000);
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1));
        Thread.sleep(10000);
        System.out.println(bucket.getAvailableTokens());
        assertTrue(bucket.tryConsume(1));
``

Resılt
``
3
2
2
1
1
0
``  
@vladimir-bukhtoyarov

**Comment by vladimir-bukhtoyarov** [comment]
@ykalayy explanation is the same https://github.com/vladimir-bukhtoyarov/bucket4j/issues/128#issuecomment-705351470

**Comment by ykalayy** [comment]
@vladimir-bukhtoyarov Yes I missed that. I got it very thanks for the explanation
