### ISSUE TITLE
Support for refilling buckets over maximum

### ISSUE THREAD

**Issue by shahr** [vladimir-bukhtoyarov/bucket4j#151]
Hi,

I'm an avid fan of bucket4j. Recently I've had a requirement where I need to add more tokens to the bucket than the limit allows. The example scenario is as follows:
- Let's assume that the user is rate limited on 2 kinds of operations: add and delete.
- We set the limit to 10 operations over a duration of a second (for example).
- However, we want to distinguish the type of operations such that when the user tries to perform an add operations more than 10 times within a second, we want to apply rate limit as normal; but if the user performs one delete operation, then an add operation - we want the net rate limit applied to be 0 (i.e. credit the bucket with a token for the delete and debit the bucket for the add operation).
- The problem comes in where if a user attempts 100 delete operations in a second, the bucket would only be credited with 10 tokens (as that is the bucket's maximum capacity). Subsequently, the user would only abe able to perform 10 add operations instead of 100 (due to prior credits that were issued for the deletes)

Based on the above scenario, would it be possible to introduce a feature to allow setting the number of available tokens to be greater than the maximum capacity of the bucket?

**Comment by vladimir-bukhtoyarov** [comment]
@shahr 

It is possible to support this feature. But I will able to do it only in March because of lack of free time.

**Comment by shahr** [comment]
That's excellent. Thank you. I am happy to wait. For now, we have a work around to use the normal rate limit and capture overflow in a separate cache then perform some logic to do the accounting. However, once the feature is ready (and I can help test it), we can remove this custom logic.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @shahr 

Desired functionality has been release under the version ```6.1.0```. You need to use **forceAddTokens** instead of **addTokens**.

**Comment by shahr** [comment]
Thanks @vladimir-bukhtoyarov - I'll test this out in the coming week.
