### ISSUE TITLE
Add support for relational databases

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#18]
All *JDBC* compatible databases with ```sql SELECT FOR UPDATE``` feature can be easy supported by Bucket4j algorithm. Steps of algorithm to solve concurrency issues are following:
- Begin transaction.
- SELECT FOR UPDATE the state of bucket.
- UPDATE the state of bucket.
- Commit transaction.

Obvious, the latency and throughput the solution based on JCache will be dramatically faster, because algorithm for JCache has single step(result achieving in one network hop), but relational database is well known solution when in-memory grids is very fresh concept, so JDBC will be a good starting point for people which need in distributed bucket, but have no time to learn or low on resources to deploy the JCache based solution.

**Comment by vladimir-bukhtoyarov** [comment]
Closed as non-perspective. Re implemention java logic as stored procedures is the single possible way to avoid performance issues.

**Comment by vladimir-bukhtoyarov** [comment]
done. Will be documented in the scope of #69

**Comment by lehphyro** [comment]
Hi, where can I find the implementation of this issue? I found this module but folders are empty: https://github.com/vladimir-bukhtoyarov/bucket4j/tree/master/experimental

**Comment by vladimir-bukhtoyarov** [comment]
Hello @lehphyro 

This feature will be released this month in the scope of ```7.0``` release. Examples can be found here https://github.com/vladimir-bukhtoyarov/bucket4j/tree/7.0/bucket4j-examples/src/test/java/example/distributed/generic/postgresql
