### ISSUE TITLE
document is error

### ISSUE THREAD

**Issue by BigXin0109** [vladimir-bukhtoyarov/bucket4j#214]
document is error：

https://bucket4j.com/7.0.0/toc.html#using-bucket-as-scheduler

2.1.3. Using bucket as scheduler
bucket.asScheduler().consume(1);

interface SchedulingBucket is not existed method  consume(long numTokens)
https://bucket4j.com/7.0.0/toc.html#scheduling-bucket

**Comment by straumat** [comment]
Indeed, the documentation indicates that you should use: `bucket.asScheduler().consume(1);` (cf. screen capture or [link to documentation](https://bucket4j.com/7.0.0/toc.html#using-bucket-as-scheduler)).

But in the source, you only have this method available: `CompletableFuture<Void> consume(long numTokens, ScheduledExecutorService scheduler);` so I don't know how to migrate from 6 to 7. Thx

![bucket](https://user-images.githubusercontent.com/536498/148839740-4f4571ac-e7a5-4439-857e-ef3e4a81ae8b.png)

**Comment by vladimir-bukhtoyarov** [comment]
Hello guys,

The method ```asScheduler``` has been renamed in 7.0.0 to ```asBlocking```

**Comment by BigXin0109** [comment]
Thanks
