### ISSUE TITLE
Is there a mechanism to identify which limit was applied when consuming a token

### ISSUE THREAD

**Issue by shahr** [vladimir-bukhtoyarov/bucket4j#215]
First of all, thanks for the fantastic library. I have a question (or potentially a feature request).

We are currently using multiple limits when configuring our bucket. e.g.
```
BucketConfiguration.builder()
                   .addLimit(Bandwidth.simple(100, Duration.ofSeconds(1)))
                   .addLimit(Bandwidth.simple(500, Duration.ofSeconds(60)))
                   .build();
```
We then consume a token via `bucket.tryConsumeAndReturnRemaining(50)` and rely on the `ConsumptionProbe` response to tell us if the consumption was successful and how many tokens are remaining.

The challenge we have at the moment is that we can't identify which limit is used for this consumption because if the consumption fails, we need to be able to indicate back to the caller whether all tokens (within the 60 seconds) have been spent or just the 100 (within 1 second) have been exhausted so the caller can wait the appropriate amount of time before re-trying the operation. It is also useful to know which limit is applied so we can provide a reason to the caller e.g. "500 tokens can consumed within 60 seconds and of those, only 100 tokens can consumed within 1 second and an attempt to consume more than 100 tokens within 1 second has been made."

An edit to note that we are using the latest version of the library (v7.0.0).

**Comment by vladimir-bukhtoyarov** [comment]
Hello @shahr 

There is special API for such cases https://bucket4j.com/7.0.0/toc.html#verbose-api

```java
VerboseResult<Boolean> verboseResult = bucket.asVerbose().tryConsume(numberOfTokens);
if (!verboseResult.getValue()) {
   Bandwidth[] bandwidths = verboseResult.getConfiguration().getBandwidths();
   VerboseResult.Diagnostics diagnostics = result.getDiagnostics()
   long[] availableTokens = verboseResult.getgetAvailableTokensPerEachBandwidth();
   List<Bandwidth> overconsumedLimits = new ArrayList();
   for(int i = 0; i < availableTokens.length; i++) {
      if (availableTokens[i] < numberOfTokens) {
          overconsumedLimits.add(bandwidths[i]);
      }
   }
   // TODO do something with overconsumedLimits
}
```
