### ISSUE TITLE
Is it possible to throttle which is not based on time

### ISSUE THREAD

**Issue by sreekanthmakam** [vladimir-bukhtoyarov/bucket4j#226]
I have a scenario where we allow only x requests to work at any point in time. More than x requests should be throttled. 

Basically, I don't want a refill based on time, I want to refill once the request is done.
For example, x requests come in, tokens are assigned. Now the bucket is empty. No other requests are allowed. once those 4 threads are done with their method, token has to come back to bucket so other requests can use it.

I was looking at this bucket4j and trying to find if this supports this.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @sreekanthmakam 

Token Bucket is not suitable for a such case. Please use [Semaphore](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html).
