### ISSUE TITLE
Distribute through maven central and change groupId and base package

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#23]
Current groupId of bucket4j is ```com.github```, but Maven Central requires that groupId of artefact should be a controlled(by author) domain, so groupId should be changed, else it is not possible to publish artefacts to Maven Central:
- Change groupId from ```com.github``` to ```com.github.vladimir-bukhtoyarov```
- Rename java package from ```com.github.bucket4j``` to ```io.github.bucket4j```, [domain for this package](https://bucket4j.github.io/) already reserved.
- Contact to Bintray support as mentioned in this topic in stackoverflow [How to change groupid if project is already uploaded to bintray](http://stackoverflow.com/a/34756610/2586973)
- Integrate [Bucket4j Bintray repo](https://bintray.com/vladimir-bukhtoyarov/maven/bucket4j) with Maven Central.

This issue originally raised in [jhipster#5388](https://github.com/jhipster/generator-jhipster/issues/5388)

Proposed to release 2.0

**Comment by jdubois** [comment]
Be careful, I'm not sure "vladimir-bukhtoyarov" is a valid Java package name. I didn't try for a (very) long time, but I remember I couldn't use "com.julien-dubois".

**Comment by vladimir-bukhtoyarov** [comment]
@jdubois yes, it is valid name. I [already distribute](https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/pom.xml#L23)  under this package name, and all works fine.

**Comment by jdubois** [comment]
Well, it looks like you should use an underscore (and I hate it!): https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by vladimir-bukhtoyarov** [comment]
I am not a fundamentalist, package name will not be changed, it will stay as is ```com.github.bucket4j```, I think it is pretty package name. Maybe for major version 2.0 I will buy personal domain ```bucket4j.com```, if so then package will be changed according to grouId, else it will stay unchanged until any serious naming conflict will happen.

**Comment by jdubois** [comment]
Sorry, I didn't realize your package name was different from your groupId, and in fact it should be, otherwise that's quite confusing.
What you could do, is what we did for for the JHipster library:

- The package name is "io.github.jhipster", as we have the domain name "https://jhipster.github.io/" for free from GitHub -> you also have "io.github.bucket4j" for free.
- And to be consistent, our groupId is also "io.github.jhipster", you can check the lib at http://search.maven.org/#artifactdetails%7Cio.github.jhipster%7Cjhipster%7C1.1.1%7Cjar

**Comment by vladimir-bukhtoyarov** [comment]
wow, using subdomain inside github.io is great idea, I missed this, thanks.

**Comment by vladimir-bukhtoyarov** [comment]
Bucket4j has been published to Maven Central:
```java
<dependency>
    <groupId>com.github.vladimir-bukhtoyarov</groupId>
    <artifactId>bucket4j-core</artifactId>
    <version>2.0.0</version>
</dependency>
<dependency>
    <groupId>com.github.vladimir-bukhtoyarov</groupId>
    <artifactId>bucket4j-jcache</artifactId>
    <version>2.0.0</version>
</dependency>
```
