### ISSUE TITLE
Add support for Caffeine

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#238]
It will be useful for bucket per key scenarios when distributed synchronization is unnecessary. Distributed synchronization can  it can be unnecessary in the following use cases:
* Request stickiness is provided by a load balancer.
* Other use-cases where stickiness can be achieved by the application itself, for example, Kafka consumer.

**Comment by vladimir-bukhtoyarov** [comment]
@pat246 hello,

Just use proper generic types for cache builder. You can find example in the tests.

**Comment by pat246** [comment]
@vladimir-bukhtoyarov Thanks. example in tests helped.
