### ISSUE TITLE
bucket4j.com is blocked due to security risk

### ISSUE THREAD

**Issue by dknc** [vladimir-bukhtoyarov/bucket4j#239]
The bucket4j.com is blocked by both Chrome and Firefox. Even I add the bucket4j.com cert chain to my trusted cert store, it is still  blocked by corporation security checker. The CA is not trusted.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @dknc 

I can not help. The site is hosted by Github Pages with a certificate provided by this hosting platform.

**Comment by vladimir-bukhtoyarov** [comment]
You can use this PDF documentation in case if problem with your Firewall can not be solved
[reference-7.2.pdf](https://github.com/vladimir-bukhtoyarov/bucket4j/files/8167057/toc.pdf)
