### ISSUE TITLE
A mising piece of code in docs

### ISSUE THREAD

**Issue by igorp1024** [vladimir-bukhtoyarov/bucket4j#253]
Hi!
There's a missing part of call chain in the docs, `.asBlocking()` in particular.

Instead of 
`if (bucket.tryConsume(1, MAX_WAIT_NANOS, BlockingStrategy.PARKING)) {`
should be 
`if (bucket.asBlocking().tryConsume(1, MAX_WAIT_NANOS, BlockingStrategy.PARKING)) {`
in docs/quick-start-examples

**Comment by vladimir-bukhtoyarov** [comment]
fixed
