### ISSUE TITLE
please delete it .

### ISSUE THREAD

**Issue by pradeepkusingh** [vladimir-bukhtoyarov/bucket4j#3]

**Comment by pradeepkusingh** [comment]
it looks to me we need atomic integer to see track of available token. am I missing something ?

**Comment by pradeepkusingh** [comment]
From 6500 to 6498 , instead of 6499, so seeing this pattern across the test.

statement first : LockFreeBucket{state=BucketState{state=[9366888527252769, 6500, 0, 100, 0]},

Statement second : LockFreeBucket{state=BucketState{state=[9366888779567345, 6498, 1290412500, 98, 19852500]},

**Comment by vladimir-bukhtoyarov** [comment]
@pradeepkusingh For the future please provide code snippet which illustrates the problem.
