### ISSUE TITLE
Get actual count of tokens in a Bucket 

### ISSUE THREAD

**Issue by stemau98** [vladimir-bukhtoyarov/bucket4j#31]
This is more a question than a issue. Hopefully anyone can help me!
Is it possible to determine the amount of token in a bucket at runtime?
I' ve read the docs but I don't see any possibility to do so?

After `bucket.tryConsume(1)` I need the amount of tokens left in the bucket!

**Comment by vladimir-bukhtoyarov** [comment]
Yes, it is possible. Before answering, I need to know your usecase, please describe it a little bit.

**Comment by stemau98** [comment]
I'm using distributed buckets to rate the limit for API calls. And I would like to set header fields like X-Rate-Limit-Remaining with the remaining tokens.

**Comment by vladimir-bukhtoyarov** [comment]
There is tricky way which I use for unit testing:
```java
Bucket bucket = null;
BucketState snapshot = bucket.createSnapshot();
long availableTokens = snapshot.getAvailableTokens(bucket.getConfiguration().getBandwidths());
```
But it is not designed to be used for production, and especially will be a performance penalty for distributed case, because **createSnapshot**  performs network request.

Your usecase looks reasonable for me, I will add new **tryConsume** variant, which returns both consumption result and remaining tokens, just wait for a week.

**Comment by stemau98** [comment]
Great to hear this! Thanks for your great support!

**Comment by vladimir-bukhtoyarov** [comment]
This issue is tightly related with #35, need to implement both together.

**Comment by vladimir-bukhtoyarov** [comment]
Implemented.  "2.1" will be release soon. Example of usage can be found in the bottom of [this page](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/2.1/doc-pages/basic-usage.md#example-3---limiting-the-rate-of-access-to-rest-api).

**Comment by stemau98** [comment]
Great work! Thanks

**Comment by vladimir-bukhtoyarov** [comment]
version 2.1.0 has been released
