### ISSUE TITLE
Any way to ask the bucket how long until next token? 

### ISSUE THREAD

**Issue by cameronbraid** [vladimir-bukhtoyarov/bucket4j#35]
I'm considering using bucket4j to rate limit calling a rate limited API. In one case I need to be able to report, if the rate limit is reached,  how long until a new token will be available. 

Is there a way to do this? 

Cheers

Cameron

**Comment by vladimir-bukhtoyarov** [comment]
Currently there is no API to achieve this in effective way. I plan to release new version "2.1" in few days. I will add this issue to the scope, it looks closely similar to main goal of release described there #31

**Comment by cameronbraid** [comment]
Thank you. That sounds great

**Comment by vladimir-bukhtoyarov** [comment]
Implemented.  "2.1" will be release soon. Example of usage can be found in the bottom of [this page](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/2.1/doc-pages/basic-usage.md#example-3---limiting-the-rate-of-access-to-rest-api).

**Comment by vladimir-bukhtoyarov** [comment]
version 2.1.0 has been released
