### ISSUE TITLE
Add support for fixed interval refill

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#39]
In opposite to smooth refill which adds token as soon as possible, interval refill should regenerate tokens periodically.

Proposed API:
```java
public static Refill fixedInterval(long tokens, Duration period) {
    // ...
}

public static Refill fixedInterval(Instant timeOfFirstRefill, long tokens, Duration period) {
     // ...
}
```

**Comment by vtahlani** [comment]
When this feature will be available?

**Comment by vladimir-bukhtoyarov** [comment]
Most likely in January 2018

**Comment by vtahlani** [comment]
I need this feature soon, can you try for oct end?

**Comment by vladimir-bukhtoyarov** [comment]
Yes, I can try, please hire me [via upwork](https://www.upwork.com/freelancers/~013d8e02a32ffdd5f5). I am agree to fixed price project 1000 US dollars.

**Comment by vladimir-bukhtoyarov** [comment]
@vtahlani do you still need in this feature?

**Comment by vtahlani** [comment]
Yes.

**Comment by vladimir-bukhtoyarov** [comment]
@vtahlani  I have a little time frame to implement new release ```3.2```, #12 and #65 already implemented, you have the good chance that "fixed interval refill" will be included to ```3.2```, to achieve this you need to describe how do you plan to use this feature from business point of view. In other words I expect the descriptions of use-cases, which can be added to javadocs and wiki-pages.

**Comment by vladimir-bukhtoyarov** [comment]
> Also as tokens get refilled in milliseconds then in a minute I would be serving more request than my limit.

This is because the token-bucket allows local burst by design. [You can not avoid the burst](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/production-generic-checklist.md#be-wary-of-short-term-bursts), independently of smoot or interval refill style. For example: 
- Having 100 tokens per minute limit.
- You decided to refresh limit each 1 minute.
- In time 1 second before refreash bucket is full. User acquires all 100 token within this second. So bucket is empty.
- After second, bucket is full again because of interval refill.
- User come again and consume a next 100 tokens for next second.
- In conclusion user consumed 200 tokens for 2 seconds.
**Redefine contract as 50 tokens per 30 second, would be single possible way to provide guarantee that user will be unable to consume more then 100 tokens per 1 minute**, and stay in same time in token-bucket model which takes minimal memory footprint and does not store each event independently from each other.
Also 

> I also faced another challenge what should be the value for X-RateLimit-Reset when should i say it would be rest.

It is interesting option, thanks for pointing out. I will add support for this for this option to the method [tryConsumeAndReturnRemaining](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java#L69), it will work for both, smooth and interval refill.

**Comment by vladimir-bukhtoyarov** [comment]
The proposed API to specifying interval refill:
```java
// 1000 tokens per minute, refill happens with one second interval
Bandwidth limit = Bandwidth.simple(1000, Duration.ofMinutes(1)).refilInterval(Duration.ofSecond(1))

Bucket bucket = Bucket4j.builder()
    .addBandwith(limit)
    .build();
```
I am not sure that ```refilInterval``` is best  name for method(resilience4j uses ```limitRefreshPeriod```), feel free to propose more suitable.

**Comment by vladimir-bukhtoyarov** [comment]
will be released soon

**Comment by vladimir-bukhtoyarov** [comment]
@vtahlani I have created dedicated issue #68 for X-RateLimit-Reset header

**Comment by vladimir-bukhtoyarov** [comment]
> if i change duration to one minute then refill would happen after one minute, right?

right

> Now in every one minute i would be able to consume only 1000 toke, right?

In general case no, see my previous comment that describes the burst.

**Comment by vladimir-bukhtoyarov** [comment]
released https://github.com/vladimir-bukhtoyarov/bucket4j/releases/tag/4.0.0
