### ISSUE TITLE
Introduce asynchronyous API

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#41]
**Reason.**
It is nice to have additional API implemented in this style, because when working with external back-ends we are introducing additional latency, and do blocking of current thread can be undesirable sometimes for end user.

**Potentional problems:**
- Several back-ends like JDBC compatible database do not provide the support of async API, so asynchronious API at Bucket4j level should be optional featture which depends from concrete back-end.
- Because JCache does not provide async API it is need to reintroduce support for particular in-memory grid(which was removed in scope of #10). Users who is not needed for async API can stay on the JCache abstraction, users who need for async api should migrate to concrete implementation. It is need to support directly following grids: Ignite, Hazelcast, Infinispan.

**Comment by lovelle** [comment]
Hi, to me the api seems quite easy to understand and use it.

One thing that maybe could be great to have is a method like '.setEventLoopGroup' in order to specify the pool of threads in which bucket4j will handle the tasks, I didn't read the implementation so I don't really know if these is even possible.

**Comment by vladimir-bukhtoyarov** [comment]
@lovelle I have a good news for you, Bucket4j does not use any threads internally, instead it relates on asynchronious functionality provided by concrete backend behind the bucket. For example see details of [Ignite](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.0/bucket4j-ignite/src/main/java/io/github/bucket4j/grid/ignite/IgniteProxy.java#L81) or [Hazelcast](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.0/bucket4j-hazelcast/src/main/java/io/github/bucket4j/grid/hazelcast/HazelcastProxy.java#L85).  That is why [JCache extension has no asynchronous support](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.0/bucket4j-jcache/src/main/java/io/github/bucket4j/grid/jcache/JCacheProxy.java#L82), because specification does not required asynchronious API.

For local bucket asynchronous API has no sense for majority of method(excepting conditional consuming with waiting limit), because latency of acquiring for local bucket is about few tens of nanoseconds, so most of asynchronous methods just do redirection to synchronous code [like this](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.0/bucket4j-core/src/main/java/io/github/bucket4j/local/LockFreeBucket.java#L220).

I will document this fact in javadocs and wiki.
