### ISSUE TITLE
Is dynamic refill strategy possible?

### ISSUE THREAD

**Issue by howryu** [vladimir-bukhtoyarov/bucket4j#42]
I was wondering if the current library supports dynamic refill strategy. i.e. the rate to refill the bucket is not fixed. I did not see any interface that expose the refill strategy to end user. In my usage, the rate to refill varies according to some other factors.

**Comment by vladimir-bukhtoyarov** [comment]
Currently dynamic refill is not supported. The next few releases will be addressed to another features like asynchronous api and expansion to another back-ends like redis, mysql, voltb. There are no plans to support dynamic refill in nearest future, so it will be better for You to find another solution or implement/adopt/fork own solution by yourself.

**Comment by vladimir-bukhtoyarov** [comment]
I have rethinked this issue yet another time and decided to support this issue in [next release](https://github.com/vladimir-bukhtoyarov/bucket4j/projects/2) 
Proposed release date - September 2017

**Comment by howryu** [comment]
Great to hear that. Thanks!

**Comment by vladimir-bukhtoyarov** [comment]
@howryu 
Because each feature of bucketj should be well documented(includes examples of usage), I need the following addtional information from you:
- More detailed scenario of usage from business point of view.
- Type of buckets which You are planning to use: local or distributed.

**Comment by howryu** [comment]
Scenario: I want to establish a service and have two rest endpoints (say A and B) for users to access my resource. One of them(A) is the async operation on the resource. And the other one(B) is used to monitor on the result of async operation of A and I want to rate limit of rest endpoint B. However, to be fair with user, how much calls that user can make on B should be depend on the rate of calling on (A). That's why I want the feature of dynamic refill strategy. 

Local token bucket is fine. (Can you introduce to me where to find the doc on distributed token bucket API?)

**Comment by vladimir-bukhtoyarov** [comment]
Why do not use [Semaphore](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html)? Just add permit to semaphore each time when call (A), and tryAcquire permit when calling (B).

There documentation for [distributed usage](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/jcache-usage.md).

**Comment by howryu** [comment]
Thank you. That's actually a good idea. I think I will be need to fork your work and implement token bucket by myself anyway since I want better control over the behavior.

**Comment by vladimir-bukhtoyarov** [comment]
Sounds reasonable. 

Feel free to ask any question(better through Gitter chat) related to your fork.
