### ISSUE TITLE
BandwidthAdjuster

### ISSUE THREAD

**Issue by nmnellis** [vladimir-bukhtoyarov/bucket4j#44]
In version 1 i was able to provide a BandwidthAdjuster to the Bucket that allowed me to dynamically set the number of max tokens a bucket can hold. How would i go about doing this in version 2?

```
Buckets.withNanoTimePrecision().withLimitedBandwidth(customBandwidthAdjuster, TimeUnit.SECONDS, 1, 0).build();
```

**Comment by vladimir-bukhtoyarov** [comment]
This feature has been removed from library. I suppose that #45 should cover your usecase, else describe it much more better.

**Comment by vladimir-bukhtoyarov** [comment]
closing as duplicate
