### ISSUE TITLE
Feature Request: Dynamic configuration of capacity.

### ISSUE THREAD

**Issue by lovelle** [vladimir-bukhtoyarov/bucket4j#45]
Hi, since this [feature](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/1.1/src/main/java/com/github/bucket4j/BandwidthAdjuster.java) seems to be deprecated, we need some method or way to be able to change current capacity configuration.

For example: we have a custom configuration capacity param for RateLimit per user's, a normal scenario in which any user change this capacity, with the actual implementation the only way to accomplish this is instantiating a new bucket builder, losing all the current consumed tokens and with no more options to start over.

I came across with the idea of having a special method like `.updateCapacity(long capacity)` having the logic that if the new capacity is greater, add tokens, otherwise remove remaining tokens if there are.

Of course you will know better than me which implementation would fit better into this feature.

Thanks!

**Comment by vladimir-bukhtoyarov** [comment]
@lovelle the unique feature of Bucket4j(which is missed in similar libraries)  is ability to configure  multiple bandwidths per bucket, so ```.updateCapacity(long capacity)``` needs at least to specify bandwidth index. But I propose better interface which will allow to change all bandwidth by single interaction:
```java
bucket.updateConfiguration(newConfiguration);
```
Implementation will be easy, so I am going to release this feature in scope of [release 3.0](https://github.com/vladimir-bukhtoyarov/bucket4j/projects/2)

**Comment by lovelle** [comment]
Sounds great to me, thanks.

**Comment by vladimir-bukhtoyarov** [comment]
will be released soon

**Comment by vladimir-bukhtoyarov** [comment]
@lovelle please try dynamic reconfiguration feature via version ```3.0.0-rc1```.

You have a few days to raise any concerns related to reconfiguration API. 
When documentation for release 3.0.0 will be done(a few days), I will do stable release ```3.0.0```, and changing the API for dynamic reconfiguration will be problematically.

**Comment by lovelle** [comment]
Ok, I'm going to test this on production env, also async api, please give me some days.

Thank you!

**Comment by vladimir-bukhtoyarov** [comment]
@lovelle  
Ok, I will wait until weekend. Pay attention that javadocs for AsyncBucket is in total mess, so it is better to use common sense to understand Async API, or ask any question directly in comments of #41.  I am going to complete javadocs for async API in few days later.

**Comment by lovelle** [comment]
Hi, everything worked as expected in production environ ! 👍 
I've just leave some feedback on #41 

Thank you very much.
