### ISSUE TITLE
Do compatibility reasearch related to JCache implementation and publish results and verification tools

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#47]
There are many non-certified implementations of JCache specification(like Ehcache) on the market. They want to increase own popularity by declaring support of  JCache API, but often only API is supported and semantic of JCache is totally ignored. Usage Bucket4j with this kind of libraries should be totally prevented. Because Buket4j is compatible only with implementations which obey the JCache specification rules(especially related to EntryProcessor execution) without any exception. The Oracle Coherence, Apache Ignite, Hazelcast are good examples of well formed implementations of JCache.

What is need to do:
- Investigate compatibility of Bucket4j with several non-certified libraries from second league, try to figure out incapability trends and common issues. Prevent usage of Bucket4j with incompatible JCache providers found in scope of this research.
- Publish the tool  which any can use to to determine compatibility of Bucket4j with any JCache implementation.

**Comment by BenderRodrigez** [comment]
I think that I should post it here. I have tried to setup Bucket4j-JCache by using Redisson as a cache provider, but GridBucketState class can't be deserealized by Jackson because empty constructor is not available in this class.
It is just the first problem, which I faced, may be it is possible to use some other serialization type through Redisson configuration, but I don't check it.

**Comment by vladimir-bukhtoyarov** [comment]
@BenderRodrigez you should to use org.redisson.codec.SerializationCodec

**Comment by BenderRodrigez** [comment]
@vladimir-bukhtoyarov Thank you for advise!

**Comment by vladimir-bukhtoyarov** [comment]
Test for compatibility investigation

```java
import javax.cache.Cache;
import javax.cache.processor.EntryProcessor;
import java.util.concurrent.CountDownLatch;

public class CompatibilityTest {

    final Cache<String, Integer> cache;


    public CompatibilityTest(Cache<String, Integer> cache) {
        this.cache = cache;
    }

    public void test() throws InterruptedException {
        String key = "42";
        int threads = 4;
        int iterations = 1000;
        cache.put(key, 0);
        CountDownLatch latch = new CountDownLatch(threads);
        for (int i = 0; i < threads; i++) {
            new Thread(() -> {
                try {
                    for (int j = 0; j < iterations; j++) {
                        EntryProcessor<String, Integer, Void> processor = (mutableEntry, objects) -> {
                            int value = mutableEntry.getValue();
                            mutableEntry.setValue(value + 1);
                            return null;
                        };
                        cache.invoke(key, processor);
                    }
                } finally {
                    latch.countDown();
                }
            }).start();
        }
        latch.await();
        int value = cache.get(key);
        if (value == threads * iterations) {
            System.out.println("Implementation which you use is compatible with Bucket4j");
        } else {
            String msg = "Implementation which you use is not compatible with Bucket4j";
            msg += ", " + (threads * iterations - value) + " writes are missed";
            throw new IllegalStateException(msg);
        }
    }

}
```

**Comment by vladimir-bukhtoyarov** [comment]
Compatibility toll has been published, research declined, because it is responsibility of developers.
