### ISSUE TITLE
How to expire tokens in a bucket??

### ISSUE THREAD

**Issue by bullsEye173** [vladimir-bukhtoyarov/bucket4j#48]
A simple question. I have the following code which limits 10 REST API calls in a minute

```
Bucket bucket = (Bucket) session.getAttribute(bucketKey);
if (bucket == null) {
	Bandwidth limit = Bandwidth.simple(10, Duration.ofMinutes(1));
	bucket = Bucket4j.builder().addLimit(limit).build();
	session.setAttribute(bucketKey, bucket);
}
// tryConsume returns false immediately if no tokens available with the bucket
if (bucket.tryConsume(1)) {
	// the limit is not exceeded
}else{
	// the limit has exceeded
}

```
I made 20 REST API calls in 1 minute and the code goes into else condition, which is the correct behavior. But then I waited fir 5 minutes and make a new REST API call and the tokens in the bucket never expire. The code still goes into else condition after 5 minutes. How I make the tokens in the bucket to expire??

**Comment by vladimir-bukhtoyarov** [comment]
Hello @bullsEye173 , 

Please provide self-executable example of problem.
