### ISSUE TITLE
How to update special bucket by key

### ISSUE THREAD

**Issue by cenggel** [vladimir-bukhtoyarov/bucket4j#49]
I'am want to use bucket4j with hazelcase backend jcache. 
When limit policy changed ,how can I change the limit bucket on runtime without restart my service?

**Comment by vladimir-bukhtoyarov** [comment]
How many bandwidths you use per bucket?

**Comment by vladimir-bukhtoyarov** [comment]
And which version of library you use?

**Comment by cenggel** [comment]
@vladimir-bukhtoyarov  thanks for replay!

I'am using bucket4j-2.1.0. 

Sorry to explain not inaccurate, I want update bucket.

```
    private javax.cache.Cache<String, GridBucketState> cache;
    private ProxyManager<String> buckets;
     // init bucket registry
    buckets = Bucket4j.extension(JCache.class).proxyManagerForCache(cache);
....
```

When want to update bucket, remove from cache  with key and call buckets.getProxy. 
It can update the bucket of key ?

```
//remove from cache
 cache.remove(key);

  // get bucket with new supplier
  Bucket bucket = buckets.getProxy(ip, configurationLazySupplier);
```

**Comment by vladimir-bukhtoyarov** [comment]
> It can update the bucket of key ?

Do you want to apply new configuration for bucket, or available tokens?

**Comment by vladimir-bukhtoyarov** [comment]
If you want to just change configuration then use following code snippet:
```java
cache.invoke(key, (Serializable & EntryProcessor<String, GridBucketState, Void>) (entry, arguments) -> {
            BucketConfiguration newConfig = Bucket4j.configurationBuilder()
                    .addLimit(Bandwidth.simple(5, Duration.ofMinutes(1)))
                    .buildConfiguration();
            
            GridBucketState previousState = entry.getValue();
            entry.setValue(new GridBucketState(newConfig, previousState.getBucketState()));
            return null;
        });
```

Since release 3.0 configuration changes will be natively supported at api level(see #41 for moew details)

**Comment by vtahlani** [comment]
Can I change the token, e.g. if i set 100 tokens initially for key(key1) now i want to change tokens to 50 for same key(key1)?

**Comment by vladimir-bukhtoyarov** [comment]
Yes you can [replaceConfiguration](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java#L196)
