### ISSUE TITLE
Implement declarative throttling on top of ByteBuddy

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#50]
TODO list:
- Design attributes and semantic for **\@Throttled** annotation.
- Implement support for **\@Throttled** annotation.
- Describe why bytebuddy would be more suitable then Lombok.

**Comment by cowwoc** [comment]
Lombok is broken at a design level. See https://github.com/rzwitserloot/lombok/issues/985 for an example of how much effort is going into something that should be relatively simple.

As an aside, I strongly recommend against using any tooling that relies on bytecode generation. It will have a poor cost/benefit in the long term. Take Lombok's experience as an example.

**Comment by vladimir-bukhtoyarov** [comment]
The functionality declined
