### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cowwoc** [vladimir-bukhtoyarov/bucket4j#63]
In https://github.com/vladimir-bukhtoyarov/bucket4j/blob/f2173775e201818c679ba7cc71016eb7244bef22/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java#L177 replace "wise versa" with "vice-versa".

**Comment by vladimir-bukhtoyarov** [comment]
@cowwoc please submit pull request.

**Comment by vladimir-bukhtoyarov** [comment]
closed by #64
