### ISSUE TITLE
Clarify Bucket.tryConsume() maxWaitTimeNanos

### ISSUE THREAD

**Issue by cowwoc** [vladimir-bukhtoyarov/bucket4j#65]
https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/basic-usage.md#example-2---using-bucket-as-scheduler mentions `bucket.tryConsume(1, BlockingStrategy.PARKING);` but Bucket4j 3.1.1 only has `Bucket.tryConsume(long numTokens, long maxWaitTimeNanos, BlockingStrategy blockingStrategy) throws InterruptedException`.

It's not clear what value needs to be passed to `maxWaitTimeNanos` to block forever.

**Comment by vladimir-bukhtoyarov** [comment]
The typo in documentation has been fixed. 

Unlimited blocking is unsupported by math foundation behind the Bucket4j, but you can use ```Long.MAX_VALUE``` that equals 292 years and can be supposed as infinite for mostly real world use cases.

**Comment by cowwoc** [comment]
Sorry, what prevents you from checking for Long.MAX_VALUE as a special value and blocking forever?

**Comment by vladimir-bukhtoyarov** [comment]
Many releases ago, it was special method that provides the API that you wish https://github.com/vladimir-bukhtoyarov/bucket4j/blob/release_1-0/src/main/java/com/github/bucket4j/Bucket.java#L81
```java
 /**
     * Consumes numTokens from the bucket. If enough tokens are not currently available then this method will block until required number of tokens will be available or current thread is interrupted.
     *
     * @param numTokens The number of tokens to consumeSingleToken from teh bucket, must be a positive number.
     *
     * @throws InterruptedException in case of current thread has been interrupted during the waiting
     */
    void consume(long numTokens) throws InterruptedException;
```
It was removed, because were corner cases when its implementation behaved in undefined/unpredictable way.

**Comment by vladimir-bukhtoyarov** [comment]
@cowwoc I have simplified the API for blocking consumption, in the next release it can be used in following manner:

### Example 2 - using bucket as scheduler
Suppose you need to have the fresh exchange rate between dollars and euros. 
To get the rate you continuously poll the third-party provider, 
and by contract with provider you should poll not often than 100 times per 1 minute, else provider will block your ip:   
```java
// define the limit 100 times per 1 minute
Bandwidth limit = Bandwidth.simple(100, Duration.ofMinutes(1));
// construct the bucket
Bucket bucket = Bucket4j.builder().addLimit(limit).build();

...
volatile double exchangeRate;
...

// do polling in infinite loop
while (true) {
  // Consume a token from the token bucket.  
  // If a token is not available this method will block until the refill adds one to the bucket.
  bucket.asBlocking().consume(1);

  exchangeRate = pollExchangeRate();
}
```

**Comment by vladimir-bukhtoyarov** [comment]
Will be released soon.

**Comment by vladimir-bukhtoyarov** [comment]
The better API for using bucket as scheduler has been released https://github.com/vladimir-bukhtoyarov/bucket4j/releases/tag/4.0.0
