### ISSUE TITLE
Getting bandwidth from bucket.

### ISSUE THREAD

**Issue by testark** [vladimir-bukhtoyarov/bucket4j#7]
Would it be possible to extend the `Bucket` interface to include a method returning information about the current status of a given bucket?

**Comment by vladimir-bukhtoyarov** [comment]
I have no objections to extend Bucket interface for diagnostic purposes. I can implement and release the version 1.1 on the weekend.

In my opinion the "Status" object should contain information about:
* The number of available token in the bucket.
* The number of available tokens per each bandwidth.

Feel free to explain your opinion about information which should be present in the status of bucket if you have different vision.

**Comment by testark** [comment]
> The number of available tokens per each bandwidth.

This would be great, and sufficient in my scenario.

**Comment by vladimir-bukhtoyarov** [comment]
Could you explain your scenario a little bit? I can review it and propose right solution.

**Comment by vladimir-bukhtoyarov** [comment]
is duplicated for #12

**Comment by tburch** [comment]
Is there a way to get the `BucketConfiguration` for an existing `Bucket`? I didn't see it in the `Bucket` interface, but maybe I overlooked that in another class.

**Comment by vladimir-bukhtoyarov** [comment]
@tburch for inmemory bucket just cast it to LocalBucket interface and use getConfiguration method. For any variant of distributed bucket you can get configuration via ProxyManager.
