### ISSUE TITLE
Distributed bucket4J read/write throughput through listener API

### ISSUE THREAD

**Issue by nitenA** [vladimir-bukhtoyarov/bucket4j#84]
I have a question regarding the read/write throughout of bucket4J scheduler API in case of using Hazelcast. Currently we have observed that tryconsume method takes around 100+ ms avg to get token.

We do use same Hazelcast infrastructure using entry processors for other direct use case and read/write throughout is under 10ms. 

Would like to know if there is any logging which can be enabled on library as server side interaction with entry processor happens within core library that can provide where is the latency.

As a next step, I will also enable Hazelcast logging to see if there is any locking happening or memory issues.

**Comment by vladimir-bukhtoyarov** [comment]
Bucket4j does not provide logging functionality, but you are able to decorate Cache/IMap that passed at construction time, and via decorator you will be able to measure/log both client and server(partially) side latency. 

How many keys is used? The differences between 10ms and 100ms can be explained by queueing if you use one or few keys.

Also if you use scheduler API then differences can be explained by parking the threads that wait to refill.

Any way, 10 and 100 it is just average if I understand correctly, it is always better to have historam of latencies.

**Comment by nitenA** [comment]
We are using scheduler API. Even if Bucket is at 30 Token per second duration, I see lot of time spent on parking thread to get token. Either we need to look the partition thread used by proxy manager at server side as I guess it’s blocking call. All read writes happens through one partition thread as there is only key (bucket).

**Comment by vladimir-bukhtoyarov** [comment]
> We are using scheduler API. Even if Bucket is at 30 Token per second duration, I see lot of time spent on parking thread to get token. 

Do you have a stacktrace? And also what is the code which used for consumption from bucket?

**Comment by nitenA** [comment]
Here is the stack trace.

container-0-C-1" #179 prio=5 os_prio=0 tid=0x0000000060116800 nid=0x55dc waiting on condition [0x000000010b2ee000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
        at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
        at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
        at com.hazelcast.client.proxy.ClientMapProxy.executeOnKeyInternal(ClientMapProxy.java:1295)
        at com.hazelcast.client.proxy.ClientMapProxy.executeOnKey(ClientMapProxy.java:1288)
        at io.github.bucket4j.grid.hazelcast.HazelcastProxy.execute(HazelcastProxy.java:46)
        at io.github.bucket4j.grid.GridBucket.execute(GridBucket.java:167)
        at io.github.bucket4j.grid.GridBucket.reserveAndCalculateTimeToSleepImpl(GridBucket.java:104)
        at io.github.bucket4j.AbstractBucket.consume(AbstractBucket.java:278)
        at io.github.bucket4j.BlockingBucket.consume(BlockingBucket.java:203)
        at com.throttler.BucketService.consumeBucket(BucketService.java:100)

**code snippet**..
HazelcastBucketBuilder e = ((Hazelcast) Bucket4j.extension(Hazelcast.class)).builder();
			Iterator arg6 = limits.iterator();

			while (arg6.hasNext()) {
				Bandwidth limit = (Bandwidth) arg6.next();
				if (Optional.ofNullable(limit).isPresent()) {
					log.info("Available limit: {}", new Object[]{limit});
					e.addLimit(limit);
				}
			}

			bucket = e.build(this.hazelCastService.getBucketMap(), bucketId, RecoveryStrategy.RECONSTRUCT);

**Comment by nitenA** [comment]
Doc states, https://docs.hazelcast.org//docs/latest-development/manual/html/Distributed_Computing/Entry_Processor/Performing_Fast_In-Memory_Map_Operations.html

NOTE: Entry processors run via Operation Threads that are dedicated to specific partitions. Therefore, with long running entry processor executions, other partition operations such as map.put(key) cannot be processed. With this in mind, it is a good practice to make your entry processor executions as quick as possible.

Respecting Locks on Single Keys

The entry processor respects locks ONLY when its executions are performed on a single key. As explained in the above section, the entry processor has the following methods to process a single key:
Object executeOnKey(K key, EntryProcessor entryProcessor);
ICompletableFuture submitToKey(K key, EntryProcessor entryProcessor);
Therefore, if you want to perform an entry processor execution on a single key using one of these methods and that key has a lock on it, the execution will wait until the lock on that key is removed

**Comment by vladimir-bukhtoyarov** [comment]
> Therefore, with long running entry processor executions, other partition operations such as map.put(key) cannot be processed. With this in mind, it is a good practice to make your entry processor executions as quick as possible.

Exactly, Bucket4j entry-processor does a very small amount of work, so it can not be a problem by itself. I run  test bellow without network(both Hazelcast client and server placed on localhost)
```java
long allowedRps = 1_000_000_000;
        Bucket bucket = Bucket4j.extension(getExtensionClass())
                .builder()
                .addLimit(Bandwidth.simple(allowedRps, Duration.ofSeconds(1)))
                .build(map, "42", RecoveryStrategy.RECONSTRUCT);

        RollingHdrHistogram histogram = RollingHdrHistogram.builder()
                .neverResetReservoir()
                .build();
        for (int i = 0; i < 10_000; i++) {
            long now = System.nanoTime();
            bucket.asScheduler().consumeUninterruptibly(1);
            histogram.update(System.nanoTime() - now);
        }
        System.out.println(histogram.getSnapshot());
```
And achieved 293 microsecond latency in average(less then 1ms), so EntryProcessor by itself can not be the cause of 100ms latency. Bellow the latency distribution in nanoseconds:
```
SmartSnapshot{
max=35651583, 
min=99328, 
mean=293263.36, 
stdDeviation=558704.2585171257, 
distribution=50.0%:185343.0; 
75.0%:309247.0; 
90.0%:483327.0; 
95.0%:774143.0; 
98.0%:1228799.0; 
99.0%:1646591.0; 
99.9%:4718591.0; 
}
```

When having 32 parallel threads the stat became is not so beautiful 1,3ms in average:
```java
 public void hazelcastLatency() throws InterruptedException {
        long allowedRps = 1_000_000_000;
        Bucket bucket = Bucket4j.extension(getExtensionClass())
                .builder()
                .addLimit(Bandwidth.simple(allowedRps, Duration.ofSeconds(1)))
                .build(map, "42", RecoveryStrategy.RECONSTRUCT);


        RollingHdrHistogram histogram = RollingHdrHistogram.builder()
                .neverResetReservoir()
                .build();

        CountDownLatch latch = new CountDownLatch(32);

        for (int i = 0; i < 32; i++) {
            new Thread(() -> {
                for (int j = 0; j < 10_000; j++) {
                    long now = System.nanoTime();
                    bucket.asScheduler().consumeUninterruptibly(1);
                    histogram.update(System.nanoTime() - now);
                }
                latch.countDown();
            }).start();
        }
        latch.await();
        System.out.println(histogram.getSnapshot());
    }
```
Letency distribution:
```
SmartSnapshot
{
max=63176703, 
min=104448, 
mean=1311908.7608, 
stdDeviation=1248804.7644849399, 
distribution=50.0%:1064959.0; 
75.0%:1122303.0; 
90.0%:1507327.0; 
95.0%:2047999.0; 
98.0%:4685823.0; 
99.0%:6225919.0; 
99.9%:1.4090239E7; 
}
```
But this expected and can be explained by huge contention on same key.

Before to go next lets make yet another check: try to specify effectively unlimited bandwidth for example 100_000_000 tokens per second, it is need to be sure that latency is not related to limit itself.

**Comment by nitenA** [comment]
thanks let me test same with my Hazelcast cluster and will be able to see if network is an issue.

**Comment by nitenA** [comment]
Verifies latency is due to limit itself. Thanks.
