### ISSUE TITLE
Adopt distributed version Bucket4j for huge request rate on single key

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#90]
**Problem:**
Because Bucket4j makes a new network request to backend on each limitation check the Bucket4j it is not well suitable for cases when the request rate is huge(tens thouthands per second), because remote backend becomes become a bottleneck.

**Solution:**
Hold bucket state locally on each node and sync consumed tokens periodically with a configured interval. Be aware of consumption rate inside cluster.

**Ideas for implementation:**
The algorithms are well described in research articles for example:
 [Cloud Control with Distributed Rate Limiting](https://www.microsoft.com/en-us/research/wp-content/uploads/2007/01/fp076-raghavan.pdf) Barath Raghavan, Kashi Vishwanath, Sriram Ramabhadran, Kenneth Yocum, and Alex C. Snoeren. Department of Computer Science and Engineering University of California, San Diego

**Limitations:**
Acting in this way may break consistency, so activation of this mode should be optional.

**Comment by vladimir-bukhtoyarov** [comment]
Implementation has been done, documentation will be created in the scope of #69

**Comment by rupebac** [comment]
Where is the documentation of the new API done in #90 ? before I could just do asScheduler().consume(1)... now I have to pass an ScheduledExecutorService? why?
