### ISSUE TITLE
AbstractBucketBuilder#buildConfiguration is protected making it inaccessible through the Extension

### ISSUE THREAD

**Issue by lchayoun** [vladimir-bukhtoyarov/bucket4j#92]
Please make it public

**Comment by vladimir-bukhtoyarov** [comment]
@lchayoun It is not a big deal to make this method public. 
But before doing that I want to know why [ConfigurationBuilder](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/ConfigurationBuilder.java) can not be used. In my proposals, this class should be used when you need only to build configuration without building the whole bucket, so I want to know when I was wrong.

**Comment by lchayoun** [comment]
Hi @vladimir-bukhtoyarov 
We use it in [AbstractBucket4jRateLimiter](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/master/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/AbstractBucket4jRateLimiter.java) of [spring-cloud-zuul-ratelimit](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit) in order to support different implementations.

currently we are unable to upgrade the bucket4j version.

If I'm using it wrong please tell me how to use the `ConfigurationBuilder` instead :)

**Comment by vladimir-bukhtoyarov** [comment]
Yes, it better to use ConfigurationBuilder because this abstraction especially created for cases when you want to build the only configuration.

**Comment by lchayoun** [comment]
`ConfigurationBuilder` constructor is protected as well, and it doesn't allow to extend an existing cache as done with the `Extension`
See example here: [Bucket4jJCacheRateLimiter](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/master/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/Bucket4jJCacheRateLimiter.java) which extends [AbstractBucket4jRateLimiter](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/master/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/AbstractBucket4jRateLimiter.java)

**Comment by vladimir-bukhtoyarov** [comment]
@lchayoun 
Constructor of ConfigurationBuilder was made protected by design in order to reduce number of entry points of API that user should know in order to interact with library. Use following code to instantiate ConfigurationBuilder
```java
Bucket4j.configurationBuilder()
```

**Comment by lchayoun** [comment]
Thanks
