### ISSUE TITLE
Refill Strategy should be an interface so that users can define their own Refill Strategies

### ISSUE THREAD

**Issue by sumitsarkar** [vladimir-bukhtoyarov/bucket4j#95]
If refill strategy were an interface, creating my own Refill Strategy dependent on external variable would be very easy. The current class defies that behaviour and even Kotlin based functions extensions are not possible because of the private constructor of the class.

Considering #13 was a welcome change to the library, I would argue to take it a step further and allow users to create their own Refill Strategies. Please let me know if you would like me to work on an example.

**Comment by vladimir-bukhtoyarov** [comment]
@sumitsarkar what is version of Bucket4j you talk about? Current version has no class RefillStrategy. There is class [Refill](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/Refill.java) but it is just a container for data without any behavior, so there is not point for which interface can be applied.

**Comment by sumitsarkar** [comment]
Sorry @vladimir-bukhtoyarov. I was talking about the Refill class. The Bucket can't be created without a Refill - it has to either a greedy approach or an intervally one.

I am stuck with figuring out a way to confirm to rate limits of an API, where I can make N requests per second. But if all the N requests take more than one second to complete, the refill strategy allows me to execute another N requests. The problem with this is, the API also enforces a concurrency limit of N reuqests.

So I have to make sure I make only N requests concurrently but also that a maximum of N requests are exeucted in a second. 

I was thinking of overriding the Refill class to implement my own refill strategy that satisfies both conditions and doesn't refill automatically. Or I could skip refilling the bucket and manually relinquish each token on completion of a request and keep track of the "N requests per second" some other way.

Could you provide some guidance on this?

**Comment by vladimir-bukhtoyarov** [comment]
@sumitsarkar did you consider to use [addTokens](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java#L131) method? It can be used when for case when you want to return token back to bucket, for example when request takes more than 1 second as in your case.

According to limitation for concurrent requests, in my opinion it is better to use another primitive like Semaphore(or even library like Hystrix). In general it is better to write concurrent code by composing the simple primitives each of theme has known properties and well tested, then trying to write huge code block that tries to solve all problems, so I argue that composition of rate-limiter and semaphore will behave more stable and will be easy to read than trying to write rate-limiter with huge functionality.

**Comment by vladimir-bukhtoyarov** [comment]
I do not know which implementation of RingBuffer you plan to use(I am not familiar with the Kotlin), but using common sense I can apologize that RingBuffer in alone will be able to control only amount of work in the progress but not the request rate. So, to control the rate you will need to combine buffer and bucket together.

**Comment by sumitsarkar** [comment]
The default implementation of RingBuffer won't. I am controlling the overwrite using the objects in the RingBuffer that contain the times at request are made and responses are received . Now that I am saying it out loud, it does seem that I am trying to reinvent the wheel that token bucket already does.

**Comment by vladimir-bukhtoyarov** [comment]
@sumitsarkar I can mark constructor package-private, but not public or protected, because it will contradicts with library architecture. 

Package private constructor:
* will be enough to make subsclassing, just place subslass in same package.
* Other users will understand that subsclassing of Refill is not typical use-case for library usage and when doing that you will understand the all risks.

If it is fine for you I can make new release today.

**Comment by sumitsarkar** [comment]
@vladimir-bukhtoyarov That makes sense. Thank you for providing a potential solution. I did manage to solve my issue two days back using pure Kotlin with backpressure built into it. So, I don't really need this feature anymore.

Since nobody else has asked for this use-case, I'd leave it to you whether you want to release this feature or not.

**Comment by vladimir-bukhtoyarov** [comment]
Great!
